# Generated by Django 2.1.15 on 2021-05-13 17:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSabt', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('CodeGroup', models.CharField(max_length=2, verbose_name='کد گروه')),
                ('TitleGroup', models.CharField(max_length=150, verbose_name='عنوان گروه')),
                ('kind', models.CharField(choices=[('2', 'سود و زیانی'), ('3', 'کنترلی'), ('1', 'ترازنامه ای')], max_length=1, verbose_name='نوع')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Company.Company', verbose_name='شرکت')),
                ('UserSabt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'گروه حسابها',
                'db_table': 'GroupAcc',
                'ordering': ['CodeGroup'],
            },
        ),
        migrations.CreateModel(
            name='GroupTaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSabt', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('CodeGroupTaf', models.CharField(max_length=5, verbose_name='کد گروه تفصیلی')),
                ('TitleGroupTaf', models.CharField(max_length=150, verbose_name='عنوان گروه تفصیلی')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Company.Company', verbose_name='شرکت')),
                ('UserSabt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'گروه تفصیلی',
                'db_table': 'GroupTaf',
                'ordering': ['CodeGroupTaf'],
            },
        ),
        migrations.CreateModel(
            name='KolAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSabt', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('CodeKol', models.CharField(max_length=5, verbose_name='کد کل')),
                ('TitleKol', models.CharField(max_length=150, verbose_name='عنوان حساب کل')),
                ('kind', models.CharField(choices=[('1', 'بدهکار مطلق'), ('2', 'بدهکار'), ('3', 'بستانکار مطلق'), ('4', 'بستانکار'), ('5', 'بدون کنترل')], max_length=1, verbose_name='نوع حساب')),
                ('CodeGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.GroupAcc', verbose_name=' گروه حساب')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Company.Company', verbose_name='شرکت')),
                ('UserSabt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'حساب کل',
                'db_table': 'KolAcc',
                'ordering': ['CodeKol'],
            },
        ),
        migrations.CreateModel(
            name='MoinAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSabt', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('CodeMoin', models.CharField(max_length=10, verbose_name='کد معین')),
                ('TitleMoin', models.CharField(max_length=150, verbose_name='عنوان حساب معین')),
                ('Kind', models.IntegerField(verbose_name='نوع')),
                ('TafRel', models.IntegerField(default=0, verbose_name='ارتباط با تفصیلی')),
                ('CodeKol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.KolAcc', verbose_name='حساب کل')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Company.Company', verbose_name='شرکت')),
                ('UserSabt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'حساب معین',
                'db_table': 'MoinAcc',
                'ordering': ['CodeMoin'],
            },
        ),
        migrations.CreateModel(
            name='MoinTafRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='سطح تفصیلی')),
                ('GroupTaf', models.ForeignKey(blank=True, null=True, on_delete='گروه تفصیلی', to='Accounts.GroupTaf')),
                ('Moin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.MoinAcc', verbose_name='حساب معین')),
            ],
            options={
                'verbose_name': 'ارتباط معین با گروه تفصیلی',
                'db_table': 'MoinTafRel',
            },
        ),
        migrations.CreateModel(
            name='Tafsili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSabt', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('CodeTafsili', models.CharField(max_length=10, verbose_name='کد تفصیلی')),
                ('TitleTafsili', models.CharField(max_length=150, verbose_name='عنوان تفصیلی')),
                ('Tozihat', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_Active', models.CharField(choices=[('0', 'غیر فعال'), ('1', 'فعال')], default='1', max_length=1, verbose_name='وضعیت فعال')),
                ('is_Tax', models.CharField(choices=[('1', 'مالیاتی'), ('2', 'غیر مالیاتی')], max_length=1, verbose_name='وضعیت مالیاتی')),
                ('CodeGroupTaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.GroupTaf', verbose_name='گروه تفصیلی')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Company.Company', verbose_name='شرکت')),
                ('UserSabt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'تفصیلی',
                'db_table': 'Tafsili',
                'ordering': ['CodeTafsili'],
            },
        ),
        migrations.AddIndex(
            model_name='tafsili',
            index=models.Index(fields=['id'], name='Tafsili_id_f6dc72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tafsili',
            unique_together={('CodeTafsili', 'Company')},
        ),
        migrations.AddIndex(
            model_name='moinacc',
            index=models.Index(fields=['id'], name='MoinAcc_id_348650_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moinacc',
            unique_together={('CodeMoin', 'Company')},
        ),
        migrations.AddIndex(
            model_name='kolacc',
            index=models.Index(fields=['id'], name='KolAcc_id_48b13e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kolacc',
            unique_together={('CodeKol', 'Company')},
        ),
        migrations.AddIndex(
            model_name='grouptaf',
            index=models.Index(fields=['id'], name='GroupTaf_id_0167e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouptaf',
            unique_together={('CodeGroupTaf', 'Company')},
        ),
        migrations.AddIndex(
            model_name='groupacc',
            index=models.Index(fields=['id'], name='GroupAcc_id_0d250b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupacc',
            unique_together={('CodeGroup', 'Company')},
        ),
    ]
